---

- name: ssh | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: ssh | systemd service drop-in dir
  file:
    path: "{{ ssh_dropin }}"
    state: directory

- name: ssh | config
  tags:
    - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dst }}/{{ item.src }}"
  loop:
    - src: sshd_config
      dst: /etc/ssh
    - src: ssh_config
      dst: /etc/ssh
    - src: iptables.conf
      dst: "{{ ssh_dropin }}"
  notify: restart ssh

- name: ssh | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes
