---

- name: ssh | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: ssh | systemd service drop-in dir
  file:
    path: "{{ ssh_dropin | dirname }}"
    state: directory

- name: ssh | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
  loop:
    - sshd_config
    - ssh_config
  notify: restart ssh

- name: ssh | firewall config
  tags:
    - config
  template:
    src: iptables.conf.j2
    dest: "{{ ssh_dropin }}"
  notify:
    - daemon-reload
    - restart ssh

- name: ssh | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes
