---

- name: OpenSSH | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: OpenSSH | server config
  tags:
    - config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh

- name: OpenSSH | client config
  tags:
    - config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config

- name: OpenSSH | iptables
  tags:
    - iptables
  iptables:
    ip_version: "{{ item | ipv4 | ternary('ipv4', 'ipv6') }}"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    source: "{{ item }}"
    jump: ACCEPT
  loop: "{{ ssh_whitelist | ipaddr }}"
  notify: iptables

- name: OpenSSH | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes
