---

- name: ssh | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: ssh | client config
  tags:
  - config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config

- name: ssh | server config
  tags:
  - config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh

- name: ssh | firewall config dir
  file:
    path: "{{ ssh_iptables_conf | dirname }}"
    state: directory

- name: ssh | firewall config
  tags:
  - config
  template:
    src: iptables.conf.j2
    dest: "{{ ssh_iptables_conf }}"
  notify:
  - daemon-reload
  - restart ssh

- name: ssh | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes
