---

- name: ssh | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: ssh | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
  loop:
  - sshd_config
  - ssh_config
  notify: restart ssh

- name: ssh | firewall config dir
  file:
    path: "{{ ssh_iptables_conf | dirname }}"
    state: directory

- name: ssh | firewall config
  tags:
  - config
  template:
    src: iptables.conf.j2
    dest: "{{ ssh_iptables_conf }}"
  notify:
  - daemon-reload
  - restart ssh

- name: ssh | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes
